{
 "title": "TP9-PART1",
 "time": { "from": "2019-10-07T21:26:43.000Z", "to": "2019-12-06T12:37:59.000Z" },
 "panels": [
  {
   "title": "Scrape duration",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_exporter_collector_duration_seconds{collector=\"collect.global_variables\"}",
     "legendFormat": "Scrape duration"
    }
   ]
  },
  {
   "title": "refused connection",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "mysql_global_status_access_denied_errors",
     "legendFormat": "refused connection"
    }
   ]
  },
  {
   "title": "READ",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mysql_global_status_innodb_data_reads",
     "legendFormat": "Total read"
    }
   ]
  },
  {
   "title": "Nombre de compte créée",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT created_at AS \"time\", id AS \"id\" FROM sylius_customer ORDER BY created_at"
    }
   ]
  },
  {
   "title": "Nombre d'utilisateurs",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(id) AS \"id\" FROM sylius_customer"
    }
   ]
  },
  {
   "title": "Somme total des commandes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 20, "x": 4, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select created_at as \"time\", sum(amount) as \"amount\" from sylius_payment group by date(time)"
    }
   ]
  },
  {
   "title": "paiement de la semaine dernière",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "select id from sylius_payment where created_at > '2019-11-24' and created_at < '2019-11-31'"
    }
   ]
  }
 ]
}