{
 "title": "TP9-PART1",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Scrape duration",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_exporter_collector_duration_seconds{collector=\"collect.global_variables\"}",
     "legendFormat": "Scrape duration"
    }
   ]
  },
  {
   "title": "refused connection",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mysql_global_status_access_denied_errors",
     "legendFormat": "refused connection"
    }
   ]
  },
  {
   "title": "READ",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mysql_global_status_innodb_data_reads",
     "legendFormat": "Total read"
    }
   ]
  }
 ]
}